# Ablation studty setting
# COCO 1% dataseed 1, random seed 1
# Multi-scale training
# 45k batch_size label: 12, unlabel: 12

# (1)baseline
# CUDA_VISIBLE_DEVICES=0,1 python train_net.py \
# --num-gpus 2 \
# --resume \
# --config configs/class_aware_cont/coco_supervision/faster_rcnn_R_50_FPN_sup1_run1.yaml \
# SOLVER.IMG_PER_BATCH_LABEL 12 SOLVER.IMG_PER_BATCH_UNLABEL 12 \
# SOLVER.STEPS '44990, 44995' \
# SOLVER.MAX_ITER 45001 \
# SOLVER.CHECKPOINT_PERIOD 2000 \
# SEMISUPNET.BURN_UP_STEP 2000 \
# SEMISUPNET.UNSUP_LOSS_WEIGHT 4.0 \
# MOCO.WARMUP_EMA False \
# MOCO.BOX_JITTERING False \
# MOCO.CONTRASTIVE_LEARNING False \
# MOCO.CLASS_AWARE_CONTRASTIVE False \
# UNCERTAINTY.PSEUDO_LABEL_REG False \
# SEED 1 \
# OUTPUT_DIR './output/ablation_study/baseline';

# (2) baseline + class-aware 
# CUDA_VISIBLE_DEVICES=2,3 python train_net.py \
# --num-gpus 2 \
# --config configs/class_aware_cont/coco_supervision/faster_rcnn_R_50_FPN_sup1_run1.yaml \
# --dist-url 'tcp://0.0.0.0:12345' \
# SOLVER.IMG_PER_BATCH_LABEL 12 SOLVER.IMG_PER_BATCH_UNLABEL 12 \
# SOLVER.STEPS '44990, 44995' \
# SOLVER.MAX_ITER 45001 \
# SOLVER.CHECKPOINT_PERIOD 2000 \
# SEMISUPNET.BURN_UP_STEP 2000 \
# SEMISUPNET.UNSUP_LOSS_WEIGHT 4.0 \
# MOCO.WARMUP_EMA False \
# MOCO.TEMPERATURE 0.07 \
# MOCO.TARGET_GENERATE_MODEL 'teacher' \
# MOCO.CONT_SCORE_THRESHOLD 0.7 \
# MOCO.CONTRASTIVE_LOSS_WEIGHT 0.2 \
# MOCO.CONTRASTIVE_LOSS_TYPE 'infoNCE' \
# MOCO.BOX_JITTERING True \
# MOCO.JITTER_FRAC 0.06 \
# MOCO.JITTER_TIMES 1 \
# MOCO.CONT_PREDICTION_HEAD True \
# MOCO.CONTRASTIVE_LEARNING True \
# MOCO.CLASS_AWARE_CONTRASTIVE True \
# MOCO.RESUME_AFTER_BURNUP True \
# MODEL.WEIGHTS 'output/ablation_study/baseline+class_aware_cont/model_burnup.pth' \
# UNCERTAINTY.PSEUDO_LABEL_REG False \
# UNCERTAINTY.UNCERTAINTY_THRESHOLD 0.0 \
# SEED 1 \
# OUTPUT_DIR './output/ablation_study/baseline+class_aware_cont_0.2_0.07';

# (3) baseline + uncertainty reg
# CUDA_VISIBLE_DEVICES=2,3 python train_net.py \
# --num-gpus 2 \
# --config configs/class_aware_cont/coco_supervision/faster_rcnn_R_50_FPN_sup1_run1.yaml \
# --dist-url 'tcp://0.0.0.0:12344' \
# SOLVER.IMG_PER_BATCH_LABEL 12 SOLVER.IMG_PER_BATCH_UNLABEL 12 \
# SOLVER.STEPS '44990, 44995' \
# SOLVER.MAX_ITER 45001 \
# SOLVER.CHECKPOINT_PERIOD 2000 \
# SEMISUPNET.BURN_UP_STEP 5000 \
# SEMISUPNET.UNSUP_LOSS_WEIGHT 4.0 \
# MOCO.WARMUP_EMA False \
# MOCO.TEMPERATURE 0.2 \
# MOCO.TARGET_GENERATE_MODEL 'teacher' \
# MOCO.CONT_SCORE_THRESHOLD 0.7 \
# MOCO.CONTRASTIVE_LOSS_WEIGHT 0.1 \
# MOCO.CONTRASTIVE_LOSS_TYPE 'infoNCE' \
# MOCO.BOX_JITTERING False \
# MOCO.JITTER_FRAC 0.06 \
# MOCO.JITTER_TIMES 1 \
# MOCO.CONT_PREDICTION_HEAD False \
# MOCO.CONTRASTIVE_LEARNING False \
# MOCO.CLASS_AWARE_CONTRASTIVE False \
# UNCERTAINTY.PSEUDO_LABEL_REG False \
# MODEL.ROI_HEADS.NAME 'ContROIHeadsPseudoLabUncertainty' \
# MODEL.ROI_BOX_HEAD.BOX_ENCODE_TYPE "xyxy" \
# MOCO.RESUME_AFTER_BURNUP True \
# MODEL.WEIGHTS 'output/ablation_study/baseline+uncertainty_reg/model_burnup.pth' \
# UNCERTAINTY.UNCERTAINTY_THRESHOLD 0.5 \
# SEED 1 \
# OUTPUT_DIR './output/ablation_study/baseline+uncertainty_reg';

# (4) baseline + uncertainty reg + uncertainty threshold
# threshold: 0.7
# CUDA_VISIBLE_DEVICES=0,1 python train_net.py \
# --num-gpus 2 \
# --config configs/class_aware_cont/coco_supervision/faster_rcnn_R_50_FPN_sup1_run1.yaml \
# --dist-url 'tcp://0.0.0.0:12344' \
# SOLVER.IMG_PER_BATCH_LABEL 12 SOLVER.IMG_PER_BATCH_UNLABEL 12 \
# SOLVER.STEPS '44990, 44995' \
# SOLVER.MAX_ITER 45001 \
# SOLVER.CHECKPOINT_PERIOD 2000 \
# SEMISUPNET.BURN_UP_STEP 5000 \
# SEMISUPNET.UNSUP_LOSS_WEIGHT 4.0 \
# SEMISUPNET.BBOX_THRESHOLD 0.7 \
# MOCO.WARMUP_EMA False \
# MOCO.CONT_PREDICTION_HEAD False \
# MOCO.CONTRASTIVE_LEARNING False \
# MOCO.CLASS_AWARE_CONTRASTIVE False \
# UNCERTAINTY.PSEUDO_LABEL_REG True \
# MODEL.ROI_HEADS.NAME 'ContROIHeadsPseudoLabUncertainty' \
# MODEL.ROI_BOX_HEAD.BOX_ENCODE_TYPE "xyxy" \
# MOCO.RESUME_AFTER_BURNUP True \
# MODEL.WEIGHTS 'output/ablation_study/baseline+uncertainty_reg/model_burnup.pth' \
# UNCERTAINTY.UNCERTAINTY_THRESHOLD 0.5 \
# SEED 1 \
# OUTPUT_DIR './output/ablation_study/baseline_0.7+uncertainty_reg+threshold_0.5';

# threshold: 0.8
# CUDA_VISIBLE_DEVICES=0,1 python train_net.py \
# --num-gpus 2 \
# --config configs/class_aware_cont/coco_supervision/faster_rcnn_R_50_FPN_sup1_run1.yaml \
# SOLVER.IMG_PER_BATCH_LABEL 12 SOLVER.IMG_PER_BATCH_UNLABEL 12 \
# SOLVER.STEPS '44990, 44995' \
# SOLVER.MAX_ITER 45001 \
# SOLVER.CHECKPOINT_PERIOD 2000 \
# SEMISUPNET.BURN_UP_STEP 5000 \
# SEMISUPNET.UNSUP_LOSS_WEIGHT 4.0 \
# SEMISUPNET.BBOX_THRESHOLD 0.8 \
# MOCO.WARMUP_EMA False \
# MOCO.CONT_PREDICTION_HEAD False \
# MOCO.CONTRASTIVE_LEARNING False \
# MOCO.CLASS_AWARE_CONTRASTIVE False \
# UNCERTAINTY.PSEUDO_LABEL_REG True \
# MODEL.ROI_HEADS.NAME 'ContROIHeadsPseudoLabUncertainty' \
# MODEL.ROI_BOX_HEAD.BOX_ENCODE_TYPE "xyxy" \
# MOCO.RESUME_AFTER_BURNUP True \
# MODEL.WEIGHTS 'output/ablation_study/baseline+uncertainty_reg/model_burnup.pth' \
# UNCERTAINTY.UNCERTAINTY_THRESHOLD 0.5 \
# SEED 1 \
# OUTPUT_DIR './output/ablation_study/baseline_0.8+uncertainty_reg+threshold_0.5';

#baseline + uncertainty reg and threshold + class-aware cont 
# CUDA_VISIBLE_DEVICES=0,1 python train_net.py \
# --num-gpus 2 \
# --config configs/class_aware_cont/coco_supervision/faster_rcnn_R_50_FPN_sup1_run1.yaml \
# SOLVER.IMG_PER_BATCH_LABEL 12 SOLVER.IMG_PER_BATCH_UNLABEL 12 \
# SOLVER.STEPS '44990, 44995' \
# SOLVER.MAX_ITER 45001 \
# SOLVER.CHECKPOINT_PERIOD 2000 \
# SEMISUPNET.BURN_UP_STEP 5000 \
# SEMISUPNET.UNSUP_LOSS_WEIGHT 4.0 \
# MOCO.WARMUP_EMA False \
# MOCO.TEMPERATURE 0.07 \
# MOCO.TARGET_GENERATE_MODEL 'teacher' \
# MOCO.CONT_SCORE_THRESHOLD 0.7 \
# MOCO.CONTRASTIVE_LOSS_WEIGHT 0.1 \
# MOCO.CONTRASTIVE_LOSS_TYPE 'infoNCE' \
# MOCO.BOX_JITTERING True \
# MOCO.JITTER_FRAC 0.06 \
# MOCO.JITTER_TIMES 1 \
# MOCO.CONT_PREDICTION_HEAD True \
# MOCO.CLASS_AWARE_CONTRASTIVE True \
# UNCERTAINTY.PSEUDO_LABEL_REG True \
# MODEL.ROI_HEADS.NAME 'ContROIHeadsPseudoLabUncertainty' \
# MODEL.ROI_BOX_HEAD.BOX_ENCODE_TYPE "xyxy" \
# UNCERTAINTY.UNCERTAINTY_THRESHOLD 0.5 \
# SEED 1 \
# OUTPUT_DIR './output/ablation_study/ours_0.1_0.07';

# CUDA_VISIBLE_DEVICES=2,3 python train_net.py \
# --num-gpus 2 \
# --config configs/class_aware_cont/coco_supervision/faster_rcnn_R_50_FPN_sup1_run1.yaml \
# --dist-url 'tcp://0.0.0.0:12344' \
# SOLVER.IMG_PER_BATCH_LABEL 12 SOLVER.IMG_PER_BATCH_UNLABEL 12 \
# SOLVER.STEPS '44990, 44995' \
# SOLVER.MAX_ITER 45001 \
# SOLVER.CHECKPOINT_PERIOD 2000 \
# SEMISUPNET.BURN_UP_STEP 5000 \
# SEMISUPNET.UNSUP_LOSS_WEIGHT 4.0 \
# MOCO.WARMUP_EMA False \
# MOCO.TEMPERATURE 0.1 \
# MOCO.TARGET_GENERATE_MODEL 'teacher' \
# MOCO.CONT_SCORE_THRESHOLD 0.7 \
# MOCO.CONTRASTIVE_LOSS_WEIGHT 0.5 \
# MOCO.CONTRASTIVE_LOSS_TYPE 'infoNCE' \
# MOCO.BOX_JITTERING True \
# MOCO.JITTER_FRAC 0.06 \
# MOCO.JITTER_TIMES 1 \
# MOCO.CONT_PREDICTION_HEAD True \
# MOCO.CLASS_AWARE_CONTRASTIVE True \
# UNCERTAINTY.PSEUDO_LABEL_REG True \
# MODEL.ROI_HEADS.NAME 'ContROIHeadsPseudoLabUncertainty' \
# MODEL.ROI_BOX_HEAD.BOX_ENCODE_TYPE "xyxy" \
# UNCERTAINTY.UNCERTAINTY_THRESHOLD 0.5 \
# SEED 1 \
# OUTPUT_DIR './output/ablation_study/ours_0.5';

# CUDA_VISIBLE_DEVICES=0,1 python train_net.py \
# --num-gpus 2 \
# --config configs/class_aware_cont/coco_supervision/faster_rcnn_R_50_FPN_sup1_run1.yaml \
# SOLVER.IMG_PER_BATCH_LABEL 12 SOLVER.IMG_PER_BATCH_UNLABEL 12 \
# SOLVER.STEPS '44990, 44995' \
# SOLVER.MAX_ITER 45001 \
# SOLVER.CHECKPOINT_PERIOD 2000 \
# SEMISUPNET.BURN_UP_STEP 5000 \
# SEMISUPNET.UNSUP_LOSS_WEIGHT 4.0 \
# MOCO.WARMUP_EMA False \
# MOCO.TEMPERATURE 0.07 \
# MOCO.TARGET_GENERATE_MODEL 'teacher' \
# MOCO.CONT_SCORE_THRESHOLD 0.7 \
# MOCO.CONTRASTIVE_LOSS_WEIGHT 0.1 \
# MOCO.CONTRASTIVE_LOSS_TYPE 'infoNCE' \
# MOCO.BOX_JITTERING True \
# MOCO.JITTER_FRAC 0.06 \
# MOCO.JITTER_TIMES 1 \
# MOCO.CONT_PREDICTION_HEAD True \
# MOCO.CLASS_AWARE_CONTRASTIVE True \
# UNCERTAINTY.PSEUDO_LABEL_REG True \
# MODEL.ROI_HEADS.NAME 'ContROIHeadsPseudoLabUncertainty' \
# MODEL.ROI_BOX_HEAD.BOX_ENCODE_TYPE "xyxy" \
# UNCERTAINTY.UNCERTAINTY_THRESHOLD 0.5 \
# SEED 1 \
# OUTPUT_DIR './output/ablation_study/ours_reg_threshold_0.2';

# CUDA_VISIBLE_DEVICES=2,3 python train_net.py \
# --num-gpus 2 \
# --config configs/class_aware_cont/coco_supervision/faster_rcnn_R_50_FPN_sup1_run1.yaml \
# --dist-url 'tcp://0.0.0.0:12342' \
# SOLVER.IMG_PER_BATCH_LABEL 12 SOLVER.IMG_PER_BATCH_UNLABEL 12 \
# SOLVER.STEPS '44990, 44995' \
# SOLVER.MAX_ITER 45001 \
# SOLVER.CHECKPOINT_PERIOD 2000 \
# SEMISUPNET.BURN_UP_STEP 5000 \
# SEMISUPNET.UNSUP_LOSS_WEIGHT 4.0 \
# MOCO.WARMUP_EMA False \
# MOCO.TEMPERATURE 0.07 \
# MOCO.TARGET_GENERATE_MODEL 'teacher' \
# MOCO.CONT_SCORE_THRESHOLD 0.7 \
# MOCO.CONTRASTIVE_LOSS_WEIGHT 0.1 \
# MOCO.CONTRASTIVE_LOSS_TYPE 'infoNCE' \
# MOCO.BOX_JITTERING True \
# MOCO.JITTER_FRAC 0.06 \
# MOCO.JITTER_TIMES 1 \
# MOCO.CONT_PREDICTION_HEAD True \
# MOCO.CLASS_AWARE_CONTRASTIVE True \
# UNCERTAINTY.PSEUDO_LABEL_REG False \
# MODEL.ROI_HEADS.NAME 'ContROIHeadsPseudoLab' \
# MOCO.RESUME_AFTER_BURNUP True \
# MODEL.WEIGHTS 'output/ablation_study/baseline+cont/model_burnup.pth' \
# SEED 1 \
# OUTPUT_DIR './output/ablation_study/baseline+cont';

# CUDA_VISIBLE_DEVICES=0,1,2,3 python train_net.py \
# --num-gpus 4 \
# --config configs/class_aware_cont/voc/voc07_voc12.yaml \
# SOLVER.IMG_PER_BATCH_LABEL 32 SOLVER.IMG_PER_BATCH_UNLABEL 32 \
# SOLVER.STEPS '45990, 45995' \
# SOLVER.MAX_ITER 46001 \
# SOLVER.CHECKPOINT_PERIOD 2000 \
# SEMISUPNET.BURN_UP_STEP 12000 \
# SEMISUPNET.UNSUP_LOSS_WEIGHT 4.0 \
# SEMISUPNET.UNSUP_REG_LOSS_WEIGHT 6.0 \
# MOCO.WARMUP_EMA False \
# MOCO.TEMPERATURE 0.07 \
# MOCO.TARGET_GENERATE_MODEL 'teacher' \
# MOCO.CONT_SCORE_THRESHOLD 0.7 \
# MOCO.CONTRASTIVE_LOSS_WEIGHT 0.1 \
# MOCO.CONTRASTIVE_LOSS_TYPE 'infoNCE' \
# MOCO.BOX_JITTERING True \
# MOCO.JITTER_FRAC 0.06 \
# MOCO.JITTER_TIMES 1 \
# MOCO.CONT_PREDICTION_HEAD True \
# MOCO.CLASS_AWARE_CONTRASTIVE True \
# UNCERTAINTY.PSEUDO_LABEL_REG True \
# MODEL.ROI_HEADS.NAME 'ContROIHeadsPseudoLabUncertainty' \
# MODEL.ROI_BOX_HEAD.BOX_ENCODE_TYPE "xyxy" \
# MODEL.WEIGHTS 'output/ablation_study/voc_07_12_ours/model_burnup.pth' \
# MOCO.RESUME_AFTER_BURNUP True \
# UNCERTAINTY.UNCERTAINTY_THRESHOLD 0.5 \
# SEED 1 \
# OUTPUT_DIR './output/ablation_study/voc_07_12_ours_reg_weight_6.0';

# CUDA_VISIBLE_DEVICES=0,1,2,3 python train_net.py \
# --num-gpus 4 \
# --config configs/class_aware_cont/voc/voc07_voc12coco20.yaml \
# SOLVER.IMG_PER_BATCH_LABEL 32 SOLVER.IMG_PER_BATCH_UNLABEL 32 \
# SOLVER.STEPS '89990, 89995' \
# SOLVER.MAX_ITER 90001 \
# SOLVER.CHECKPOINT_PERIOD 2000 \
# SEMISUPNET.BURN_UP_STEP 12000 \
# SEMISUPNET.UNSUP_LOSS_WEIGHT 4.0 \
# MOCO.WARMUP_EMA False \
# MOCO.TEMPERATURE 0.07 \
# MOCO.TARGET_GENERATE_MODEL 'teacher' \
# MOCO.CONT_SCORE_THRESHOLD 0.7 \
# MOCO.CONTRASTIVE_LOSS_WEIGHT 0.1 \
# MOCO.CONTRASTIVE_LOSS_TYPE 'infoNCE' \
# MOCO.BOX_JITTERING True \
# MOCO.JITTER_FRAC 0.06 \
# MOCO.JITTER_TIMES 1 \
# MOCO.CONT_PREDICTION_HEAD True \
# MOCO.CLASS_AWARE_CONTRASTIVE True \
# UNCERTAINTY.PSEUDO_LABEL_REG True \
# MODEL.ROI_HEADS.NAME 'ContROIHeadsPseudoLabUncertainty' \
# MODEL.ROI_BOX_HEAD.BOX_ENCODE_TYPE "xyxy" \
# UNCERTAINTY.UNCERTAINTY_THRESHOLD 0.5 \
# OUTPUT_DIR './output/ablation_study/voc_07_12coco20_ours';

# coco-additional
# CUDA_VISIBLE_DEVICES=0,1 python train_net.py \
# --num-gpus 2 \
# --config configs/class_aware_cont/coco_additional/faster_rcnn_R_50_FPN_focal_cross_coco_unsupW2.yaml \
# SOLVER.IMG_PER_BATCH_LABEL 16 SOLVER.IMG_PER_BATCH_UNLABEL 16 \
# MOCO.WARMUP_EMA False \
# MOCO.TEMPERATURE 0.07 \
# MOCO.TARGET_GENERATE_MODEL 'teacher' \
# MOCO.CONT_SCORE_THRESHOLD 0.7 \
# SEMISUPNET.UNSUP_REG_LOSS_WEIGHT 4.0 \
# MOCO.CONTRASTIVE_LOSS_WEIGHT 0.1 \
# MOCO.CONTRASTIVE_LOSS_TYPE 'infoNCE' \
# MOCO.BOX_JITTERING True \
# MOCO.JITTER_FRAC 0.06 \
# MOCO.JITTER_TIMES 1 \
# MOCO.CONT_PREDICTION_HEAD True \
# MOCO.CLASS_AWARE_CONTRASTIVE True \
# UNCERTAINTY.PSEUDO_LABEL_REG True \
# MODEL.ROI_HEADS.NAME 'ContROIHeadsPseudoLabUncertainty' \
# MODEL.ROI_BOX_HEAD.BOX_ENCODE_TYPE "xyxy" \
# UNCERTAINTY.UNCERTAINTY_THRESHOLD 0.5 \
# MODEL.WEIGHTS 'output/ablation_study/coco-additional_ours/model_burnup.pth' \
# MOCO.RESUME_AFTER_BURNUP True \
# OUTPUT_DIR './output/ablation_study/coco-additional_ours';

# CUDA_VISIBLE_DEVICES=2,3 python train_net.py \
# --num-gpus 2 \
# --config configs/voc/voc07_voc12.yaml \
# --dist-url 'tcp://0.0.0.0:12344' \
# SOLVER.IMG_PER_BATCH_LABEL 16 SOLVER.IMG_PER_BATCH_UNLABEL 16 \
# SOLVER.STEPS '44990, 45995' \
# SOLVER.MAX_ITER 45001 \
# SOLVER.CHECKPOINT_PERIOD 2000 \
# SEMISUPNET.UNSUP_LOSS_WEIGHT 4.0 \
# SEMISUPNET.Trainer "baseline" \
# MOCO.WARMUP_EMA False \
# MODEL.ROI_HEADS.NAME 'StandardROIHeadsPseudoLabUncertainty' \
# MODEL.ROI_BOX_HEAD.BOX_ENCODE_TYPE "xyxy" \
# OUTPUT_DIR './output/ablation_study/voc_07_12_sup';

CUDA_VISIBLE_DEVICES=2,3 python train_net.py \
--num-gpus 2 \
--config configs/class_aware_cont/coco_supervision/faster_rcnn_R_50_FPN_sup1_run1.yaml \
--dist-url 'tcp://0.0.0.0:12355' \
SOLVER.IMG_PER_BATCH_LABEL 16 SOLVER.IMG_PER_BATCH_UNLABEL 16 \
SOLVER.STEPS '179990, 179995' \
SOLVER.MAX_ITER 180001 \
SOLVER.CHECKPOINT_PERIOD 2000 \
SEMISUPNET.BURN_UP_STEP 5000 \
SEMISUPNET.UNSUP_LOSS_WEIGHT 4.0 \
MOCO.WARMUP_EMA False \
MOCO.TEMPERATURE 0.07 \
MOCO.TARGET_GENERATE_MODEL 'teacher' \
MOCO.CONT_SCORE_THRESHOLD 0.7 \
MOCO.CONTRASTIVE_LOSS_WEIGHT 0.1 \
MOCO.CONTRASTIVE_LOSS_TYPE 'infoNCE' \
MOCO.BOX_JITTERING True \
MOCO.JITTER_FRAC 0.06 \
MOCO.JITTER_TIMES 1 \
MOCO.CONT_PREDICTION_HEAD True \
MOCO.CLASS_AWARE_CONTRASTIVE True \
UNCERTAINTY.PSEUDO_LABEL_REG True \
MODEL.ROI_HEADS.NAME 'ContROIHeadsPseudoLabUncertainty' \
MODEL.ROI_BOX_HEAD.BOX_ENCODE_TYPE "xyxy" \
UNCERTAINTY.UNCERTAINTY_THRESHOLD 0.5 \
OUTPUT_DIR './output/coco_standard/ours_0.01_1';