CUDA_VISIBLE_DEVICES=0,1 python train_net.py \
--num-gpus 2 \
--config configs/class_aware_cont/coco_supervision/faster_rcnn_R_50_FPN_sup1_run1.yaml \
--dist-url 'tcp://0.0.0.0:12344' \
SOLVER.IMG_PER_BATCH_LABEL 12 SOLVER.IMG_PER_BATCH_UNLABEL 12 \
SOLVER.STEPS '44990, 44995' \
SOLVER.MAX_ITER 45001 \
SOLVER.CHECKPOINT_PERIOD 2000 \
SEMISUPNET.BURN_UP_STEP 5000 \
SEMISUPNET.UNSUP_LOSS_WEIGHT 4.0 \
MOCO.WARMUP_EMA False \
MOCO.TEMPERATURE 0.07 \
MOCO.TARGET_GENERATE_MODEL 'teacher' \
MOCO.CONT_SCORE_THRESHOLD 0.7 \
MOCO.CONTRASTIVE_LOSS_WEIGHT 0.1 \
MOCO.CONTRASTIVE_LOSS_TYPE 'infoNCE' \
MOCO.BOX_JITTERING True \
MOCO.JITTER_FRAC 0.06 \
MOCO.JITTER_TIMES 1 \
MOCO.CONT_PREDICTION_HEAD True \
MOCO.CLASS_AWARE_CONTRASTIVE True \
UNCERTAINTY.PSEUDO_LABEL_REG True \
MODEL.ROI_HEADS.NAME 'ContROIHeadsPseudoLabUncertainty' \
MODEL.ROI_BOX_HEAD.BOX_ENCODE_TYPE "xyxy" \
UNCERTAINTY.UNCERTAINTY_THRESHOLD 0.3 \
SEED 1 \
OUTPUT_DIR './output/ablation_study/ours_reg_threshold_0.3';

CUDA_VISIBLE_DEVICES=2,3 python train_net.py \
--num-gpus 2 \
--config configs/class_aware_cont/coco_supervision/faster_rcnn_R_50_FPN_sup1_run1.yaml \
--dist-url 'tcp://0.0.0.0:12344' \
SOLVER.IMG_PER_BATCH_LABEL 12 SOLVER.IMG_PER_BATCH_UNLABEL 12 \
SOLVER.STEPS '44990, 44995' \
SOLVER.MAX_ITER 45001 \
SOLVER.CHECKPOINT_PERIOD 2000 \
SEMISUPNET.BURN_UP_STEP 5000 \
SEMISUPNET.UNSUP_LOSS_WEIGHT 4.0 \
MOCO.WARMUP_EMA False \
MOCO.TEMPERATURE 0.07 \
MOCO.TARGET_GENERATE_MODEL 'teacher' \
MOCO.CONT_SCORE_THRESHOLD 0.7 \
MOCO.CONTRASTIVE_LOSS_WEIGHT 0.1 \
MOCO.CONTRASTIVE_LOSS_TYPE 'infoNCE' \
MOCO.BOX_JITTERING True \
MOCO.JITTER_FRAC 0.06 \
MOCO.JITTER_TIMES 1 \
MOCO.CONT_PREDICTION_HEAD True \
MOCO.CLASS_AWARE_CONTRASTIVE True \
UNCERTAINTY.PSEUDO_LABEL_REG True \
MODEL.ROI_HEADS.NAME 'ContROIHeadsPseudoLabUncertainty' \
MODEL.ROI_BOX_HEAD.BOX_ENCODE_TYPE "xyxy" \
UNCERTAINTY.UNCERTAINTY_THRESHOLD 0.4 \
MOCO.RESUME_AFTER_BURNUP True \
MODEL.WEIGHTS 'output/ablation_study/ours_reg_threshold_0.4/model_burnup.pth' \
SEED 1 \
OUTPUT_DIR './output/ablation_study/ours_reg_threshold_0.4';