_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  META_ARCHITECTURE: "TwoStagePseudoLabGeneralizedRCNN_cont"
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  PROPOSAL_GENERATOR:
    NAME: "PseudoLabRPN"
  RPN:
    POSITIVE_FRACTION: 0.25
    LOSS: "CrossEntropy"
  ROI_HEADS:
    NAME: "ContROIHeadsPseudoLabUncertainty"
    LOSS: "FocalLoss" # variant: "CrossEntropy"
SOLVER:
  LR_SCHEDULER_NAME: "WarmupTwoStageMultiStepLR"
  STEPS: (60000, 80000, 90000, 360000)
  FACTOR_LIST: (1, 1, 1, 1, 1)
  MAX_ITER: 360001
  IMG_PER_BATCH_LABEL: 16
  IMG_PER_BATCH_UNLABEL: 16
  BASE_LR: 0.01
DATALOADER:
  SUP_PERCENT: 100.0
DATASETS:
  CROSS_DATASET: True
  TRAIN_LABEL: ("coco_2017_train",)
  TRAIN_UNLABEL: ("coco_2017_unlabel",)
  TEST: ("coco_2017_val",)
SEMISUPNET:
  Trainer: "class_aware_cont"
  BBOX_THRESHOLD: 0.7
  TEACHER_UPDATE_ITER: 1
  BURN_UP_STEP: 90000
  EMA_KEEP_RATE: 0.9996
  UNSUP_LOSS_WEIGHT: 2.0
TEST:
  EVAL_PERIOD: 1000
OUTPUT_DIR: './output/coco_1.0/mocov3_trial_1'
MOCO:
  QUEUE_SIZE: 50000
  CONTRASTIVE_FEATURE_DIM: 128
  TEMPERATURE: 0.07
  LABELED_CONTRASTIVE_IOU_THRES: 0.8
  PSEUDO_LABEL_JITTERING: True
  CONTRASTIVE_LOSS_VERSION: 'v2'
  CONTRASTIVE_LOSS_WEIGHT: 0.1
  CLASSWISE_QUEUE: False
  QUEUE_UPDATE_LABEL_WITH_BACKGROUND: True
  WARMUP_EMA: False
