_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  META_ARCHITECTURE: "TwoStagePseudoLabGeneralizedRCNN_cont"
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  PROPOSAL_GENERATOR:
    NAME: "PseudoLabRPN"
  RPN:
    POSITIVE_FRACTION: 0.25
    LOSS: "CrossEntropy"
  ROI_HEADS:
    NAME: "ContROIHeadsPseudoLabUncertainty"
    LOSS: "FocalLoss"
    NUM_CLASSES: 20
  ROI_BOX_HEAD:
    BOX_ENCODE_TYPE: "xyxy"
INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  MIN_SIZE_TEST: 600
SOLVER:
  LR_SCHEDULER_NAME: "WarmupMultiStepLR"
  STEPS: (179990, 179995)
  MAX_ITER: 180000
  IMG_PER_BATCH_LABEL: 16
  IMG_PER_BATCH_UNLABEL: 32
  BASE_LR: 0.01
  CHECKPOINT_PERIOD: 3000
DATALOADER:
  SUP_PERCENT: 100.0
DATASETS:
  CROSS_DATASET: True
  TRAIN: ("voc_2012_trainval",)
  TRAIN_LABEL: ("voc_2007_trainval",)
  TRAIN_UNLABEL: ("voc_2012_trainval",)
  TEST: ("voc_2007_test",)
SEMISUPNET:
  Trainer: "cont_uncertainty"
  BBOX_THRESHOLD: 0.7
  TEACHER_UPDATE_ITER: 1
  BURN_UP_STEP: 30000
  EMA_KEEP_RATE: 0.9996
  UNSUP_LOSS_WEIGHT: 4.0
TEST:                         
  EVAL_PERIOD: 3000
  EVALUATOR: "COCOeval"
  VAL_LOSS: True
MOCO:
  CONT_SCORE_THRESHOLD: 0.7
  CONTRASTIVE_LOSS_WEIGHT: 0.5
  WARMUP_EMA: True
  TEMPERATURE: 0.2
  TARGET_GENERATE_MODEL: "teacher"
  CONTRASTIVE_LOSS_TYPE: 'infoNCE'
  CONT_PREDICTION_HEAD: True
  BOX_JITTERING: False
  CONTRASTIVE_FEATURE_DIM: 128
  CONT_PREDICTION_HEAD: True
UNCERTAINTY:
  THRESHOLD: 0.4
  