_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  META_ARCHITECTURE: "TwoStagePseudoLabGeneralizedRCNN_MoCo"
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  PROPOSAL_GENERATOR:
    NAME: "PseudoLabRPN"
  RPN:
    POSITIVE_FRACTION: 0.25 # detectron2 default is 0.5
    LOSS: "CrossEntropy"
  ROI_HEADS:
    NAME: "MoCov2ROIHeadsPseudoLab"
    LOSS: "CrossEntropy" # ubteacher defaults is focal loss 
    BATCH_SIZE_PER_IMAGE: 512
SOLVER:
  LR_SCHEDULER_NAME: "WarmupMultiStepLR"
  STEPS: (59990, 59995)
  MAX_ITER: 60000
  IMG_PER_BATCH_LABEL: 6
  IMG_PER_BATCH_UNLABEL: 6
  BASE_LR: 0.01
DATALOADER:
  SUP_PERCENT: 1.0
  RANDOM_DATA_SEED: 1
DATASETS:
  CROSS_DATASET: False
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)
SEMISUPNET:
  Trainer: "mocov2"
  BBOX_THRESHOLD: 0.7 # for pseudo label
  TEACHER_UPDATE_ITER: 1
  BURN_UP_STEP: 2000
  EMA_KEEP_RATE: 0.9996
  UNSUP_LOSS_WEIGHT: 2.0
TEST:
  EVAL_PERIOD: 1000
OUTPUT_DIR: './output/coco_1.0/mocov2_trial_1'
MOCO:
  QUEUE_SIZE: 50000
  CONTRASTIVE_FEATURE_DIM: 128
  TEMPERATURE: 0.1
  LABELED_CONTRASTIVE_IOU_THRES: 0.8
  PSEUDO_LABEL_JITTERING: True
  CONTRASTIVE_LOSS_VERSION: 'v2'
  CONTRASTIVE_LOSS_WEIGHT: 0.1
  CLASSWISE_QUEUE: False
  QUEUE_UPDATE_LABEL_WITH_BACKGROUND: True